version: '3'

services:
  main:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes: ["./rest_api:/opt/rest_api"]
    environment:
      PORT: "5000"
      FLASK_DEBUG: "true"
    ports:
      - "5000:8080"